sudo: false
language: node_js
node_js:
  - "4.1"
  - "0.12"
  - "0.11"
  - "0.10"
matrix:
  allow_failures:
    - node_js: "0.11"

before_install:
  - curl --location http://rawgit.com/twolfson/fix-travis-ci/master/lib/install.sh | bash -s

before_script:
  # Generate a virtual framebuffer X server to collect Atom windows
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # Wait for Xvfb to start
  - sleep 3

script:
  # DEV: Debugging Travis CI, pretty sure we need an Xvfb
  # TODO: Remove this debug logic
  - time ./node_modules/.bin/electron lib/electron-launcher.js --url=http://google.com/

notifications:
  email: false
